/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Title: Tommy Gun
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./gun.glb')

  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group position={[-2.581, 141.727, 208.355]} scale={0.555}>
          <mesh geometry={nodes['aim_low_Material_#26_0'].geometry} material={materials.Material_26} position={[9.352, 4.121, -12.651]} />
        </group>
        <group position={[-229.938, 99.591, 208.353]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.384}>
          <mesh geometry={nodes['backBottom_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, 0.964]} />
        </group>
        <group position={[-237.367, 118.918, 208.355]} rotation={[0, -Math.PI / 2, 0]} scale={0.511}>
          <mesh geometry={nodes['backScrew_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, 0.964]} />
        </group>
        <group position={[244.153, 127.661, 208.333]} rotation={[0, Math.PI / 2, 0]} scale={0.511}>
          <mesh geometry={nodes['barrel_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, -11.395, -296.801]} />
        </group>
        <group position={[-72.089, 89.536, 208.355]} scale={0.511}>
          <mesh geometry={nodes['base_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-75.962, 60.606, 55.329]} />
        </group>
        <group position={[19.045, 129.156, 188.805]} rotation={[-2.793, 0, 0]} scale={0.511}>
          <mesh geometry={nodes['cylinderPlate_low_Material_#26_0'].geometry} material={materials.Material_26} position={[31.216, 0, -6.273]} />
        </group>
        <group position={[342.162, 141.506, 208.333]} rotation={[0, Math.PI / 2, 0]} scale={0.511}>
          <mesh geometry={nodes['fin_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, -39.04, -488.685]} />
        </group>
        <group position={[-95.778, 24.817, 208.355]} scale={0.511}>
          <mesh geometry={nodes['gripB_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-29.583, 187.314, 55.329]} />
        </group>
        <group position={[106.385, 83.257, 220.606]} rotation={[0, 0, 2.007]} scale={0.511}>
          <mesh geometry={nodes['gripF_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-13.663, 96.206, 46.474]} />
        </group>
        <group position={[109.58, 107.16, 208.259]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.264}>
          <mesh geometry={nodes['gripFscrew1_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -0.68]} />
        </group>
        <group position={[124.245, 107.16, 208.259]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.264}>
          <mesh geometry={nodes['gripFscrew2_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -0.68]} />
        </group>
        <group position={[148.008, 23.502, 189.816]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={0.511}>
          <mesh geometry={nodes['gripStrip_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-12.46, 0.108, -10.939]} />
        </group>
        <group position={[26.078, 34.583, 208.355]} rotation={[0, -Math.PI / 2, 0]} scale={0.511}>
          <mesh geometry={nodes['magB_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, 0, 19.017]} />
        </group>
        <group position={[5.597, 84.329, 209.6]} rotation={[0, Math.PI / 2, 0]} scale={0.246}>
          <mesh geometry={nodes['magBackPlate_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, -14.309, -8.703]} />
        </group>
        <group position={[6.713, 69.239, 182.843]} rotation={[0, -Math.PI / 2, 0]} scale={0.174}>
          <mesh geometry={nodes['magBackPlateScrew1_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, 0, -5.867]} />
        </group>
        <group position={[6.713, 64.752, 234.471]} rotation={[0, -Math.PI / 2, 0]} scale={0.174}>
          <mesh geometry={nodes['magBackPlateScrew2_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, 0, -5.867]} />
        </group>
        <group position={[5.915, 34.583, 207.739]} rotation={[0, -Math.PI / 2, 0]} scale={0.486}>
          <mesh geometry={nodes['magBCylinder_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, 0, 18.941]} />
        </group>
        <group position={[47.153, 34.545, 208.745]} rotation={[0, Math.PI / 2, 0]} scale={0.428}>
          <mesh geometry={nodes['magFCylinder_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, 0, 18.941]} />
        </group>
        <group position={[47.855, 84.329, 209.6]} rotation={[0, Math.PI / 2, 0]} scale={0.246}>
          <mesh geometry={nodes['magFrontPlate_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, -14.309, -8.703]} />
        </group>
        <group position={[46.726, 64.752, 184.678]} rotation={[0, Math.PI / 2, 0]} scale={0.174}>
          <mesh geometry={nodes['magFrontPlate2_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, 0, -5.867]} />
        </group>
        <group position={[46.726, 64.752, 234.471]} rotation={[0, Math.PI / 2, 0]} scale={0.174}>
          <mesh geometry={nodes['magFrontPlateScrew1_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, 0, -5.867]} />
        </group>
        <group position={[56.505, 35.408, 194.51]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.582}>
          <mesh geometry={nodes['magPart1_low_Material_#31_0'].geometry} material={materials.Material_31} position={[16.473, -21.256, -164.119]} />
        </group>
        <group position={[4.792, 34.583, 216.54]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={0.585}>
          <mesh geometry={nodes['magScrewDriver_low_Material_#31_0'].geometry} material={materials.Material_31} position={[15.047, 0, 19.854]} />
        </group>
        <group position={[54.532, 41.512, 180.497]} rotation={[0, Math.PI / 2, 0]} scale={0.215}>
          <mesh geometry={nodes['magSpinScrew1_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, 0, -0.68]} />
        </group>
        <group position={[54.532, 29.199, 180.497]} rotation={[0, Math.PI / 2, 0]} scale={0.215}>
          <mesh geometry={nodes['magSpinScrew2_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, 0, -0.68]} />
        </group>
        <group position={[-247.635, 94.657, 208.391]} rotation={[-Math.PI / 2, -0.262, 0]} scale={[0.485, 0.485, 0.575]}>
          <mesh geometry={nodes['metalButton_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -1.813]} />
        </group>
        <group position={[-190.338, 140.628, 208.355]} rotation={[-Math.PI / 2, 0, 0]} scale={0.511}>
          <mesh geometry={nodes['numberPlate_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-52.802, 0, 1.122]} />
        </group>
        <group position={[-192.754, 141.095, 197.598]} rotation={[Math.PI, 0, Math.PI]} scale={[0.193, 0.193, 0.128]}>
          <mesh geometry={nodes['numberPlateScrew_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -1.375]} />
        </group>
        <group position={[-102.379, 89.307, 219.355]} scale={0.511}>
          <mesh geometry={nodes['plate1screw2_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -232.437]} />
        </group>
        <group position={[-60.405, 84.455, 219.855]} scale={0.253}>
          <mesh geometry={nodes['plate1screw3_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -232.437]} />
        </group>
        <group position={[-27.229, 90.878, 220.379]} scale={[0.908, 0.908, 0.601]}>
          <mesh geometry={nodes['plate1screw4_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -1.375]} />
        </group>
        <group position={[-9.103, 81.44, 218.142]} scale={[0.908, 0.908, 0.601]}>
          <mesh geometry={nodes['plate1screw6_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -1.375]} />
        </group>
        <group position={[-75.202, 91.264, 198.367]} rotation={[Math.PI, 0, Math.PI]} scale={[1.193, 1.193, 0.79]}>
          <mesh geometry={nodes['plate2screw3_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -1.375]} />
        </group>
        <group position={[-218.813, 138.672, 224.685]} scale={[0.595, 0.595, 0.394]}>
          <mesh geometry={nodes['rearsightScrew1_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -1.657]} />
        </group>
        <group position={[-190.324, 143.85, 208.355]} scale={0.511}>
          <mesh geometry={nodes['sightBase_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, -0.736, 27.691]} />
        </group>
        <group position={[-299.65, 11.869, 208.355]} rotation={[0, Math.PI / 2, 0]} scale={0.511}>
          <mesh geometry={nodes['stock_low_Material_#26_0'].geometry} material={materials.Material_26} position={[73.687, 138.622, 289.65]} />
        </group>
        <group position={[-235.402, 92.899, 208.358]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.43, 0.43, 0.511]}>
          <mesh geometry={nodes['stockMetal1_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-45.409, 0, -119.121]} />
        </group>
        <group position={[-153.451, 91.211, 208.355]} rotation={[0, Math.PI / 2, 0]} scale={0.511}>
          <mesh geometry={nodes['stockMetal2_low_Material_#26_0'].geometry} material={materials.Material_26} position={[73.687, -16.716, 3.418]} />
        </group>
        <group position={[-438.099, -9.395, 208.355]} rotation={[0, Math.PI / 2, 0]} scale={0.511}>
          <mesh geometry={nodes['stockPlate_low_Material_#26_0'].geometry} material={materials.Material_26} position={[73.687, 180.252, 560.709]} />
        </group>
        <group position={[-378.326, -41.123, 208.3]} rotation={[Math.PI / 2, 0.507, 0]} scale={0.511}>
          <mesh geometry={nodes['stockStrip_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-12.46, 0.108, -10.939]} />
        </group>
        <group position={[-55.038, 87.719, 194.828]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.645}>
          <mesh geometry={nodes['switch1_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 6.776, -2.931]} />
        </group>
        <group position={[-91.952, 92.547, 194.828]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.645}>
          <mesh geometry={nodes['switch2_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 6.776, -2.931]} />
        </group>
        <group position={[26.742, 34.583, 208.355]} rotation={[0, Math.PI / 2, 0]} scale={0.511}>
          <mesh geometry={nodes['magF_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, 0, 19.017]} />
        </group>
        <group position={[-378.585, -48.989, 207.903]} rotation={[0, Math.PI / 2, 0]} scale={0.474}>
          <mesh geometry={nodes['shape1_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-16.646, 0, -4.945]} />
        </group>
        <group position={[148.057, 15.116, 189.925]} scale={0.474}>
          <mesh geometry={nodes['shape2_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-16.646, 0, -4.945]} />
        </group>
        <group position={[-29.409, 89.917, 198.367]} rotation={[Math.PI, 0, Math.PI]} scale={[1.06, 1.06, 0.702]}>
          <mesh geometry={nodes['plate2screw2_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -1.375]} />
        </group>
        <group position={[-18.968, 91.556, 198.367]} rotation={[Math.PI, 0, Math.PI]} scale={[1.06, 1.06, 0.702]}>
          <mesh geometry={nodes['plate2screw1_low_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 0, -1.375]} />
        </group>
        <group position={[5.597, 84.329, 209.6]} rotation={[0, Math.PI / 2, 0]} scale={0.246}>
          <mesh geometry={nodes['twoof_low_Material_#31_0'].geometry} material={materials.Material_31} position={[0, -14.309, -8.703]} />
        </group>
        <mesh geometry={nodes['backBottomSphere_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-229.915, 97.388, 208.34]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.433} />
        <mesh geometry={nodes['backScrewSphere_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-240.295, 118.887, 208.338]} rotation={[0, -Math.PI / 2, 0]} scale={0.575} />
        <mesh geometry={nodes['barrelCylinder_low_Material_#26_0'].geometry} material={materials.Material_26} position={[343.534, 132.366, 195.448]} scale={0.511} />
        <mesh geometry={nodes['magOpen_low_Material_#31_0'].geometry} material={materials.Material_31} position={[49.182, 35.053, 209.816]} rotation={[0, Math.PI / 2, 0]} scale={[0.438, 0.439, 0.439]} />
        <mesh geometry={nodes['magPart2_low_Material_#31_0'].geometry} material={materials.Material_31} position={[53.373, 35.248, 198.295]} rotation={[0, Math.PI / 2, 0]} scale={0.582} />
        <mesh geometry={nodes['numberPlate2_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-201.03, 141.201, 208.355]} rotation={[-Math.PI / 2, 0, 0]} scale={0.511} />
        <mesh geometry={nodes['numberPlate3_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-187.164, 144.554, 208.308]} rotation={[-Math.PI / 2, 0, 0]} scale={0.511} />
        <mesh geometry={nodes['numberPlateScrew2_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-187.609, 141.002, 197.371]} rotation={[Math.PI, 0, -Math.PI]} scale={0.585} />
        <mesh geometry={nodes['plate1screw1_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-77.343, 89.419, 100.633]} scale={0.511} />
        <mesh geometry={nodes['sightCylinder_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-192.964, 138.112, 208.355]} rotation={[0, Math.PI / 2, 0]} scale={0.511} />
        <mesh geometry={nodes['triangle_low_Material_#26_0'].geometry} material={materials.Material_26} position={[203.03, 110.864, 208.259]} scale={0.45} />
        <mesh geometry={nodes['trigger_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-38.127, 70.2, 208.355]} scale={0.511} />
        <mesh geometry={nodes['triggerPlate1_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-76.987, 89.164, 216.241]} scale={0.511} />
        <mesh geometry={nodes['triggerPlate2_low_Material_#26_0'].geometry} material={materials.Material_26} position={[-3.921, 57.837, 199.309]} scale={0.511} />
        <mesh geometry={nodes['bullet_low_Material_#90_0'].geometry} material={materials.Material_90} position={[16.376, 110.899, 208.214]} rotation={[0, Math.PI / 2, 0]} scale={0.38} />
        <mesh geometry={nodes['bullet_low_Material_#90_0_1'].geometry} material={materials.Material_90} position={[16.376, -18.387, 437.934]} rotation={[0, Math.PI / 2, 0]} scale={0.38} />
      </group>
    </group>
  )
}

useGLTF.preload('/gun.glb')